# Generated by Django 6.0.7 on 2026-07-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
