# Generated by Django 6.0.7 on 2026-07-21 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone ne doit contenir que des chiffres, espaces ou un signe +.', regex='^[\\d+\\s]*$')]),
        ),
    ]
